apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-leqs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-leqs
    app.kubernetes.io/part-of: integ-app-tsnc
  name: hacbs-test-project-leqs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-leqs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-leqs
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-avkn-tenant/integ-app-tsnc/hacbs-test-project-leqs@sha256:9e97db85a1b073abcef7b09e22f0cc41e6ab3c8c98d73cbbfd164458de09c482
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
